title: Abi's Homepage
author: Abi Mooney
# email: abim831@gmail.com
description: > # this means to ignore newlines until "baseurl:" Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  This is currently a sandbox page. I'm just testing for now, but hope to get real content up soon. 
  Thanks for your interest in my work!  
theme: minima

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  a-mooney # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
